---
title: "data_trans"
format: html
editor: visual
---

```{r}
#| label: setup
library(tidyverse)
```

```{r}
#| paged.print: false
data.frame(x = rnorm(2000), y = rnorm(2000, 2, 4))
```

```{r}
#| paged.print: false
mtcars
```

```{r}
#| paged.print: false
mtcars |>
  as_tibble() |> 
  arrange(cyl, hp) |> 
  print(n = 32)
```

```{r}
#| paged.print: false
mtcars |>
  as_tibble(rownames = "model") |> 
  arrange(cyl) |> 
  print(n = 32)
```

```{r}
#| paged.print: false
my_mtcars <- mtcars |>
  as_tibble(rownames = "model") |> 
  select(model:wt) |>
  select(model, vekt = wt, everything()) |> 
  arrange(cyl, desc(model)) |> 
  print(n = 32)
```

```{r}
#| paged.print: false
my_mtcars
```

Velge et subset:

```{r}
my_mtcars |> 
  filter(cyl == 6) |>
  select(model) |>
  arrange(model) |>
  pull()
```

```{r}
my_mtcars |>
  group_by(cyl) |>
  summarise(mean_hp = round(mean(hp), digits = 1))
```

```{r}
my_mtcars |>
  group_by(cyl) |>
  summarise(mean_disp = round(mean(disp), digits = 1))
```

Lage nye variabler:

```{r}
my_mtcars <- my_mtcars |>
  mutate(
    hp_vs_disp = hp/disp
  )
```

```{r}
my_mtcars |>
  group_by(cyl) |>
  summarise(mean_hp_vs_disp = round(mean(hp_vs_disp), digits = 3))
```
